# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b32064aac3ef7927c6aff0dd4bee89af8d66acc4cc47e3fd7532b10a08389ce600fb4376a36984df81ea606feae6a15fe7fd4b59291a9b71fe765a8977f25e37

test:
  secret_key_base: 9e42d71e25088a197c3b83096df837e6da4ac99d0ed8900dc674abcef9a118dca89dae2d95c11f55c47e3119043fb0b46556241c4ead1b84fe5068af4d91c53f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
